#!/usr/bin/env bash
set -u

usage() {
    echo "Usage: $0 <targets> <marks_per_target> <output_file> [seed]" >&2
}

if [ "$#" -lt 3 ] || [ "$#" -gt 4 ]; then
    usage
    exit 1
fi

TARGETS="$1"
MARKS="$2"
OUTPUT="$3"
SEED="${4:-42}"

if ! [[ "$TARGETS" =~ ^[0-9]+$ ]] || ! [[ "$MARKS" =~ ^[0-9]+$ ]] || [ "$TARGETS" -le 0 ] || [ "$MARKS" -le 0 ]; then
    echo "Ошибка: число целей и отметок должно быть положительным целым" >&2
    exit 1
fi

if ! [[ "$SEED" =~ ^[0-9]+$ ]]; then
    echo "Ошибка: seed должен быть неотрицательным целым" >&2
    exit 1
fi

RANDOM="$SEED"

rand_between() {
    local min="$1"
    local max="$2"
    echo $(( min + RANDOM % (max - min + 1) ))
}

rand_double() {
    local whole
    local frac

    whole=$(rand_between 0 359)
    frac=$(rand_between 0 9)
    printf "%d.%d" "$whole" "$frac"
}

mkdir -p "$(dirname "$OUTPUT")"

VALID_LINES=()

time_ms=1000
target_id=1

while [ "$target_id" -le "$TARGETS" ]; do
    mark_num=0
    while [ "$mark_num" -lt "$MARKS" ]; do
        range_m=$(rand_between 5000 90000)
        azimuth=$(rand_double)
        line=$(printf "%d %d %d %s" "$time_ms" "$target_id" "$range_m" "$azimuth")
        VALID_LINES+=("$line")
        time_ms=$((time_ms + 1000))
        mark_num=$((mark_num + 1))
    done
    target_id=$((target_id + 1))
done

{
    echo "# time_ms  target_id  range_m  azimuth_deg"
    echo "# generated by gen_test.sh seed=${SEED}"

    for line in "${VALID_LINES[@]}"; do
        echo "$line"
    done

    echo "broken line with two fields only"
    echo "5000 1 10000"
    echo "6000 2 15000 400.0"
    echo "7000 3 -100 45.0"
    echo "8000"
    echo "9000 4 20000 359.9 extra_field"

    duplicate_count=2
    if [ $((RANDOM % 2)) -eq 0 ]; then
        duplicate_count=3
    fi

    dup_index=0
    while [ "$dup_index" -lt "$duplicate_count" ]; do
        pick=$(rand_between 0 $((${#VALID_LINES[@]} - 1)))
        IFS=' ' read -r dup_time dup_target _ _ <<< "${VALID_LINES[$pick]}"
        dup_range=$(rand_between 1000 4000)
        dup_azimuth=$(rand_double)
        printf "%d %d %d %s\n" "$dup_time" "$dup_target" "$dup_range" "$dup_azimuth"
        dup_index=$((dup_index + 1))
    done
} > "$OUTPUT"

echo "Сгенерирован файл: $OUTPUT (seed=${SEED})" >&2
